### ISSUE TITLE
Fast autocomplete on Win10

### ISSUE THREAD

**Issue by vmc4u** [wearefair/fast-autocomplete#8]
Hello!

I wanted to try out fast autocomplete in one of my projects, running on Python 3.6 and Windows 10.

I installed all fast autocomplete packages correctly, but on importing AutoComplete I get an error:
![Capture](https://user-images.githubusercontent.com/7777541/61529355-cc54c780-aa29-11e9-90e5-53661571d587.JPG)
`from fast_autocomplete import AutoComplete` triggers ModuleNotFundError: No module named 'termios'

I looked up the 'termios' module on the web and it appears to be available only for Unix.

Is there a way to make fast autocomplete run on Windows?

Thank you!

**Comment by seperman** [comment]
Hi @vmc4u 
We use termios only for the "demo" mode and not actual production use of fast-autocomplete. We can make it optional.

**Comment by seperman** [comment]
@vmc4u I just published a new version of fast-autocomplete that makes the demo code optional. Please upgrade the `fast-autocomplete` to the latest version.

**Comment by vmc4u** [comment]
Thank you @seperman !
I'll try the new version.
All the best!
